blog_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>", views.ReadArticleView.as_view(), name="read_article"),
    path("create_article", views.CreateArticleView.as_view(), name="create_article"),
]

core/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
        
    def was_published_recently(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=1)
    
    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Article


class IndexView(generic.ListView):
    template_name = "articles/index.html"
    context_object_name = "latest_articles_list"
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Article.objects.order_by("-created_at")[:5]


class ReadArticleView(generic.DetailView):
    model = Article
    template_name = "articles/read.html"


class CreateArticleView(generic.CreateView):
    model = Article
    fields = ["title", "text"]
    template_name = "articles/create.html"
    
    def post(self, request):
        article = Article(title=request.POST['title'], text=request.POST['text'])
        article.save()
        return render(request, "articles/created.html")
    

core/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create article</title>
</head>
<body>
  <h1> Create article</h1>
    <form action="{% url 'core:create_article' %}" method="post">
      {% csrf_token %}
      {{ form.as_table }}
      <input type="submit" value="Submit">
    </form>
    
</body>
</html>

core/templates/articles/created.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Success!</title>
</head>
<body>
  <h1> Your article was created successfully!</h1>
  <a href="{% url 'core:index' %}"><button>Go back to Index</button></a>
</body>
</html>

core/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    Posts:
    {% if latest_articles_list %}
    <ul>
    {% for article in latest_articles_list.all %}
        <li><a href="{% url 'core:read_article' article.id %}">{{ article.title }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'core:create_article' %}"><button>Create article</button></a>
    {% else %}
    <p>No posts are available.</p>
    <p>No posts!</p>
    {% endif %}
</body>
</html>

core/templates/articles/read.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ article.title }} by {{ article.author }}</title>
</head>
<body>
  <h2>
    {{ article.title }}
  </h2>
  <p>
    {{ article.text }}
  </p>
  <p>
    Created at: {{ article.created_at }}<br>
    Updated at: {{ article.updated_at }}
  </p>
</body>
</html>